version: '2.2'

services:
  app:
    build: .
    pid: host
    ports:
      - "8765:8765"
    volumes:
      - .:/app
      - /var/log:/host_logs:ro  
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "src/server.py"]
