version: '3.8'

services:
  app:
    build: .
    pid: host
    ports:
      - "8765:8765"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "src/server.py"]
